name: Sync Upstream

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: master
          upstream_sync_repo: opawg/user-agents-v2

      - name: Trigger package CI/CD
        if: steps.sync.outputs.has_new_commits == 'true'
        run: |
          curl -X POST https://api.github.com/repos/the-podcast-host/user-agents-v2-api/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PERSONAL_ACCESS_TOKEN }} \
          --data '{"event_type": "ci_cd"}'
